name: Report Update

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '* */6 * * *'

jobs:
  report-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
          python3 -m pip install -r requirements-notebook.txt
      - name: Report Update
        run: python3 -m jupyter nbconvert --to notebook --execute RadarCOVID-Report.ipynb
      - name: Commit Report Update
        uses: EndBug/add-and-commit@v4
        with:
          author_name: GitHub Action - Report Update
          author_email: report-update@action.github.com
          message: "[RadarCOVID-Report] Updated Report"
          add: "*.ipynb"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
